[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neura_ai"
version = "0.1.0"
description = "Assistente IA com mem√≥ria e voz"
dependencies = [
    "ollama",
    "pyfiglet",
    "SpeechRecognition",
    "pyttsx3",
    "pyaudio"
]